### ISSUE TITLE
Enhancement: custom image run support

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [mostafa/firefighter#1]
It will be useful if `./run_microvm.sh start custom_image_name` is added.

Possible procedure to add custom_image:

- Add custom image in /image folder (rootfs and kernel name should be the same).
- refer the custom_image name in run command like above mentioned cmd.

**Comment by mostafa** [comment]
Hey @KarthikNedunchezhiyan,

I was thinking about having a config file for such images and then load and parse it via some method, but you can easily store your kernel and rootfs images in `images/` directory and refer to them with filenames:
```bash
$ ./run_microvm.sh images/vmlinuz.bin images/rootfs.ext4
```
